apiVersion: v1

kind: ConfigMap

metadata:

  name: transportation-config

  namespace: transportation

data:

  COMPANY_NAME: "Fast Transportation"

  SUPPORT_EMAIL: "support@example.com"

  VERSION: "1.0"
