apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: transportation-ingress

  namespace: transportation

spec:

  rules:

  - host: transportation.local

    http:

      paths:

      - path: /

        pathType: Prefix

        backend:

          service:

            name: transportation-service

            port:

              number: 80
